Background color changed
ShwetKhatri2001/AR-Webstore pull request #187
Opened 2023-12-21 12:30 UTC by Souvik34

Custom scroll bar
hover effects on nav  bar

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

2023-12-21 14:57 UTC, ShwetKhatri2001 requested changes
First, raise an issue and wait till you get assigned before start working. 

Talking about the changes, the background color needs to be light so that all text elements can be clearly visible. Also, change the orange color being used to some other colour near to new background color you choose.

2023-12-21 14:57 UTC, ShwetKhatri2001 commented on src/components/Header/styles.css
No need to add this long script if we are not using all variables.

2023-12-21 16:22 UTC, Souvik34 commented
I have removed the extra code part of css. It was kept for testing.

2023-12-22 20:20 UTC, ShwetKhatri2001 commented
Good, have a look at other suggested improvements then we can merge this.

2023-12-23 13:23 UTC, Souvik34 commented
Updated the color of scroll bar

2023-12-23 20:32 UTC, ShwetKhatri2001 commented
Can you change with these colours,
Background color : #e3e8ed
Scroll thumb color : #68707a

I can merge this after that.

2023-12-23 21:40 UTC, ShwetKhatri2001 approved these changes
LGTM 🎊 Congrats @Souvik34 on your first PR getting merged on AR-Webstore  🚀 Keep Contributing 👍

2023-12-23 21:42 UTC, merged