Error 404 page added and changes made
ShwetKhatri2001/AR-Webstore pull request #68
Opened 2023-06-14 20:40 UTC by VC6378

Heyy, 
Error 404 page has been added!!

2023-06-15 17:55 UTC, ShwetKhatri2001 requested changes
Make this small change and see why the deployment-preview is failing, try to fix that please.

2023-06-15 17:55 UTC, ShwetKhatri2001 commented on package-lock.json
I guess this package-lock.json is creating a problem for netlify-deployment. 

Try this : 
- Delete `package-lock.json` file ( not package.json ) and `node_modules` folder
- Install the dependencies again using `npm install`, run the app using `npm start` and check if all your changes are working fine and then commit the changed file.

2023-06-15 17:55 UTC, ShwetKhatri2001 commented on src/components/ModelViewer/Error404.js
> +
Please change the above function and redirect using  useNavigate ( from react-router-dom )
Ref : https://stackoverflow.com/questions/34735580/how-to-do-a-redirect-to-another-route-with-react-router

2023-06-16 11:50 UTC, VC6378 commented
@ShwetKhatri2001 I tried deleting and doing the same, but it did not work. Do you have some other options?

2023-07-06 08:00 UTC, ShwetKhatri2001 commented
@VC6378 You can update your PR now. Pull the latest master branch. You shouldn't be getting any deployment-related errors. 
react-router is added there now. So, you just need to update this PR and make the small code change as I mentioned earlier: https://github.com/ShwetKhatri2001/AR-Webstore/pull/68#discussion_r1231364908

2023-07-11 14:46 UTC, ShwetKhatri2001 commented
Any updates or issues @VC6378  ?
Please try to complete the requested changes and update your PR within the next 3 days.
After that, This issue will be open to other interested contributors.

2023-07-23 14:14 UTC, ShwetKhatri2001 commented
Closing this PR because it has been inactive for a long time and the issue is resolved now.

2023-07-23 14:14 UTC, closed without merging