website name updated and item align center
ShwetKhatri2001/AR-Webstore pull request #93
Opened 2023-06-28 08:17 UTC by mandliyarajendra11

## Fixes Issue
closed #84 

## Changes proposed
1. add description meta tag , and change website name from react app to AR-Webstore
2. align item to the center , remove App css code because its not working  .app classname is not defined 
and add some css in body tag 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2023-06-28 21:05 UTC, ShwetKhatri2001 requested changes
The `index.html` file is already good to go with all required meta tags now, so you can pull the latest `master` branch and can accept those changes ( not yours ) while resolving merge conflicts.

Your other changes can be merged after that.

2023-06-29 04:47 UTC, mandliyarajendra11 commented
> The `index.html` file is already good to go with all required meta tags now, so you can pull the latest `master` branch and can accept those changes ( not yours ) while resolving merge conflicts.
> 
> Your other changes can be merged after that.

done solved

2023-06-29 08:41 UTC, ShwetKhatri2001 commented
LGTM 🎉Congrats on your first PR getting merged on AR-Webstore @mandliyarajendra11 🚀 Keep Contributing 👍

2023-06-29 08:41 UTC, ShwetKhatri2001 approved these changes

2023-06-29 08:43 UTC, merged